GothenburgBitFactory/timewarrior

ext/totals.py

I got the following error when I tried to run totals.py while a task was not finished:
Traceback (most recent call last):
File "/home/davis/.timewarrior/extensions/totals.py", line 101, in <module>
end = datetime.datetime.strptime(configuration['temp.report.end'], DATEFORMAT)
KeyError: 'temp.report.end'
This change fixed that for me.

Fixed error from totals.py while timer is active

---

doc/man/timew.1.in

Hello,
Like #34 I was confused about the differing behavior in `timew day`. This pull request trys to clarify the axis docs.
Regards
Simon

Docs: try to clarify reports.<type>.axis description

---

README.md

* The github repository `HEAD` already points to `dev`, so that's the branch that will be checked out when cloning.
* `--recurse-submodules` will initialize the submodule(s).

Simplify clone instructions

---

src/Interval.cpp

#138 Escape '"' in tags for JSON output

---

AUTHORS
ChangeLog
doc/man/timew.1.in
src/CLI.cpp
src/CLI.h
src/commands/CmdTag.cpp
src/commands/CmdUntag.cpp
test/basetest/testing.py
test/delete.t
test/tag.t
test/untag.t

Adds the ability to add/remove tags to/from the current open interval without stating its id.
Closes #21.

#21 Add/Remove tags to/from current interval

---

src/CLI.cpp
test/ids.t

This fixes out-of-bounds accesses in several subcommands when the invalid ID `@0` is passed to the program.

CLI: Ensure IDs are non-zero

---

src/commands/CmdSummary.cpp

When showing a summary, set the end time to the current time on the last day only. This prevents over-counting of time when a tracked interval covers multiple days.
Fixes test `TestSummary.test_with_open_interval` when the system time is between midnight and 01:00 AM.

CmdSummary: Do not extend end time beyond end of day

---

.gitignore

Running 'make test' generates 'ext/totals.pyc', which should not be under version control.

Add *.pyc files to .gitignore

---

src/Database.cpp
src/Datafile.cpp
src/Range.cpp
src/Range.h
src/data.cpp
test/resize.t
test/summary.t

This pull request introduces two additional methods, `segmentContains` and `intersects`, that are needed to correctly handle empty intervals.
Fixes #101
Fixes #165
Closes #164

Handle zero-width intervals correctly

---

src/Database.cpp
src/commands/CmdJoin.cpp
src/util.cpp
test/tag.t

Two commits that eliminate segment faults when attempting to join intervals and when the tags database is missing "count" member for a particular tag name.

Fix segfaults on join command and invalid tags database.

---

src/CLI.cpp
test/help.t

This change makes any instance of '--help' on the command line to be made the
command for this particular invocation.
Also note, this isn't something I hit very often but just wanted to take the opportunity to use the issue to learn another part of the code since I use timewarrrior every day.

#212: "--help" should show help, not considered to be a tag.

---

ext/on-modify.timewarrior

Fixes the following error with Python 3.6.8:
```
File "$HOME/.task/hooks/on-modify.timewarrior", line 33                                                                                                                                                                                                                                                                                                                    
from __future__ import print_function                                                                                                                                                                                                                                                                                           
SyntaxError: from __future__ imports must occur at the beginning …
```

on-modify.timewarrior: Fix "from __future__ imports must occur at the beginning of the file"

---

ext/on-modify.timewarrior

If the description contained multiple lines, it would be formatted as a
bytes object, including Python's `b""` marker for byte literals and any
newlines.  This would then be passed literally to `timew`, which would
then choke on it, because it would record the newlines in its database.
This patch simply gets rid of the string join/split operations and the
encoding, which solves the issue.
Since we pass arrays instead of strings to `subprocess.call`, we are not
subject to command injection security vulnerabilities.
Fixes: 0b6dbf7e12d30fc791a524501e3483989a092a8c

Fix on-modify.timewarrior hook for tasks with multi line description

---

ext/on-modify.timewarrior

When input data from taskwarrior (e.g. via bugwarrior) contains UTF-8-illegal characters, `on-modify.timewarrior` would fail:
```
Traceback (most recent call last):
File "$HOME/.task/hooks/on-modify.timewarrior", line 42, in <module>
old = json.loads(sys.stdin.readline())
File "/usr/lib/python3.6/codecs.py", line 321, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 1042: invalid continuation byte
```
This is fixed by manually decoding from stdin's underlying binary I/O object and replacing encoding errors with the Unicode replacement character [1].
[1]: https://docs.python.org/3/library/codecs.html#error-handlers

on-modify.timewarrior: Deal with non-UTF-8 characters in input data from taskwarrior

---

ext/totals.py
test/test_totals.t

The report of the totals extension loses time if the tracked intervals for a tag sum up to more than 24 hours.
datetime.timedelta stores days, seconds and microseconds. Therefore the seconds attribute only stores timedeltas of less than 24 hours. Use total_seconds() instead which properly accounts for the days part.

Fix calculation of totals longer than a day

---

src/commands/CmdStop.cpp
test/stop.t

Recently I was trying to stop an interval that I had left open over the
weekend, but I had already started a new interval at the beginning of the
week. The error I was received was "The end of a date range must be after the
start." which was confusing to me.
After a few moments I realized I should have been using the modify command.
Now the stop command will suggest this if someone tries.

Stop with id should suggest modify command

---

src/Database.cpp
src/Database.h
src/Datafile.cpp
src/Datafile.h
src/Interval.h
src/TagInfoDatabase.cpp
src/TagInfoDatabase.h
src/commands/CmdAnnotate.cpp
src/commands/CmdContinue.cpp
src/commands/CmdDelete.cpp
src/commands/CmdJoin.cpp
src/commands/CmdLengthen.cpp
src/commands/CmdModify.cpp
src/commands/CmdMove.cpp
src/commands/CmdResize.cpp
src/commands/CmdShorten.cpp
src/commands/CmdSplit.cpp
src/commands/CmdTag.cpp
src/commands/CmdUntag.cpp
src/data.cpp
src/dom.cpp
src/helper.cpp
src/timew.h
test/annotate.t
test/modify.t
test/move.t
test/performance-test.sh
test/simpletap/__init__.py

This merge request improves the performance when there are many entries in the database by not loading or parsing all the lines in many cases where it is not necessary.
Related to issue #245

Do not load entire database for all commands

---

test/problems
test/start.t
test/stop.t
test/track.t

I was running into an issue recently where I thought I added a problem to a test, but it was failing on the current dev branch but `make test` was not reporting the errors since it was aborting without writing a "not ok" line.
Ultimately my problem was that I a) did not have python3-dateutil installed and run_all was switched to using python3 and b) My locale was not set to use UTF-8 encoding and there were unicode characters in the docstrings in 3 of the python test files.

Report when tests do not run

---

src/Database.cpp

NOTE: This change is in #283 as well since it was needed to pass the tests.
This fixes an error I introduced in the recent code to avoid loading the
entire database. It only now appeared because I happened to run the test
suite on the first of the month.
Below is the error I was seeing:
```
$ test/delete.t
1..5
ok 1 - delete.t: Delete a single closed interval
ok 2 - delete.t: Delete an interval which encloses a month border
ok 3 - delete.t: Delete a mix of open/closed intervals
not ok 4 - delete.t: Delete a single open interval
ok 5 - delete.t: Delete an open interval that spans over an exclusion
```
The problem is that when there was one entry in the 2020-01.data file
and one in the 2020-02.data file, when I deleted the single one in the
2020-02.data file, the interator constructor was …

Database: Fix error when empty datafile is most recent / oldest

---

src/Interval.cpp

Passes the `id` of an interval to extensions. Now, stdin of an extension looks like this:
```
{"id":99,"start":"20191219T183718Z","end":"20191219T185724Z","annotation":"project:gaming"},
{"id":98,"start":"20191219T211035Z","end":"20191219T220034Z","tags":["project:gaming"]},
{"id":97,"start":"20200107T090000Z","end":"20200107T113235Z","tags":["tempo:ABC-477"]},
{"id":96,"start":"20200107T125607Z","end":"20200107T152439Z","tags":["tempo:ABC-477"]},
{"id":95,"start":"20200107T165000Z","end":"20200107T180803Z","tags":["tempo:ABC-477"]},
{"id":94,"start":"20200108T081022Z","end":"20200108T083142Z","tags":["tempo:ABC-477"]},
```
Resolves #285

285: Pass interval id to extensions

---

src/Datafile.cpp
src/Interval.cpp
src/Interval.h
src/log.cpp

While this does not fix the underlying problems, I do think it to be a generally advisable change to prevent updates to the database that can not be parsed.
Ensure that the IntervalFactory can parse the string returned by
Interval::serialize before writing to database.
If a user attempts to add a non-parseable date, you will get an error like:
$ TZ="GMT" timew track 7h before 1970-01-01T00:00:00 test
Note: 'test' is a new tag.
Internal error. Failed encode / decode check.
Or if the user attempts to add a tag that is not supported:
$ timew start 1970-01-01T00:00:00 '\"TEST\"'
Note: '"\\"TEST\\""' is a new tag.
Internal error. Failed encode / decode check.
On #159, the serializer / deserializer should be able to handle the escaped
quotes, but it is another example where we do not want any …

#290 check serialization before committing to database

---

src/Interval.cpp
src/Interval.h
src/data.cpp
src/timew.h
test/summary.t

This fixes a bug I introduced in the change where the database is not fully loaded, and adds a test to check for non-contiguous result sets when filtering by tags.
Closes #293

#293 filtering by tag can produce wrong ids

---

src/IntervalFactory.cpp

When the Lexer breaks a line into tokens, it also wants to return the
type of the token. This information isn't used by the IntervalFactory
and it slows down the operation since dates end up being parsed at least
twice, once by the Lexer to determine that the string is a date, then
again in the IntervalFactory to actually construct the Date.
Before are the before and after results when exporting a database with
100 lines. The number of instructions executed went from roughly 31,552,467 to
12,952,372 on debug builds. Release builds saw a change from around 14K
to 7K instructions.
Before:
$ rm -fr ~/.timewarrior; src/timew :yes >/dev/null; for x in {100..1}; do src/timew start ${x}sec ago proj_${x} >/dev/null; done;
$ sudo chrt -f 99 valgrind --tool=callgrind …

Speed up deserialization of Intervals

---

src/Database.cpp
src/IntervalFactory.cpp

The json::object pointer was allocated in the parse function but never
freed.
The way timwarrior is used currently, this leak does not cause any
problems, but...
Signed-off-by: Shaun Ruffell <sruffell@sruffell.net>

Fix memory leak in JSON parsing

---

src/TagInfoDatabase.cpp

This makes it easier to compare and merge the tags file from different machines.

Write tags.data with one entry per line.

---

src/AtomicFile.cpp
src/AtomicFile.h
src/Datafile.cpp
src/Journal.cpp
src/Journal.h
src/Rules.cpp
src/init.cpp
test/AtomicFileTest.cpp
test/undo.t

On some of my systems, my undo file was getting very large. This change introduces a 'max_undo_entries' configuration item that is set to 0/unlimited by default, but for someone who would like timewarrior to automatically limit it to something, then they can allow timewarrior to do this.
I started looking into this since, with the introduction of AtomicFile, the large undo files were copied as part of any new transaction.  Therefore, limiting the size of the undo file *may* be faster depending on the limit that is set (lower is faster) and the speed of the storage where the database is kept.

Introduce 'journal.size' configuration item

---

src/commands/CmdHelp.cpp

Fixes the following errors when compiling on FreeBSD 12.1:
[ 75%] Building CXX object src/commands/CMakeFiles/commands.dir/CmdHelp.cpp.o
/home/user/timew-1.3.0/src/commands/CmdHelp.cpp:123:13: error: use of undeclared identifier 'WIFEXITED'
return (WIFEXITED (ret)) ? WEXITSTATUS (ret) : -1;
^
/home/user/timew-1.3.0/src/commands/CmdHelp.cpp:123:32: error: use of undeclared identifier 'WEXITSTATUS'
return (WIFEXITED (ret)) ? WEXITSTATUS (ret) : -1;
^
2 errors generated.
*** Error code 1
Thanks @kbcb
Related to issue #258
Signed-off-by: Shaun Ruffell <sruffell@sruffell.net>

CmdHelp: Include wait.h for exit() support.

---

src/commands/CmdDiagnostics.cpp
src/commands/CmdReport.cpp

I had a broken symbolic link in my extensions directory. When I ran
`timew diag` it would simply print on the screen:
```
stat error 2: No such file or directory
```
After this change, there is more context information about the source of
the error:
```
timew 1.3.0
Platform: Linux
Compiler:
Version: 7.5.0
Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
Compliance: C++11
Build Features
Built: Aug 14 2020 05:57:06
Commit: 6fe15d26
CMake: 3.10.2
Build type: Debug
Configuration
TIMEWARRIORDB: -
Cfg: /home/sruffell/.timewarrior/timewarrior.cfg (-rw- 0 bytes)
Database: /home/sruffell/.timewarrior (drwx 4096 bytes)
$EDITOR: vim
Color theme: Built-in default
00 01 02 03 04 05 06 07 08 09 10 11 12
Extensions
Location: /home/sruffell/.timewarrior/extensions (drwx 4096 bytes) …
```

CmdDiagnostics: Show per-file error messages.

---

src/commands/CmdSummary.cpp
test/summary.t

CmdSummary: Show recent intervals that start later in day than first interval with :all
It was possible for `summary` command, when used with the :all hint, to
skip over any intervals that start later than the first interval in the
database.
You can see below how the BAR interval is not displayed in the summary:
```
$ export ISOFMT="+%Y-%m-%dT%H:%M:%S"
$ timew track $(date -d 'yesterday + 5 min' $ISOFMT) for 1h FOO
Create new database in /home/sruffell/.timewarrior? (yes/no) yes
Note: 'FOO' is a new tag.
Recorded FOO
Started 2020-08-31T07:48:34
Ended              08:48:34
Total               1:00:00
$ timew start BAR
Note: 'BAR' is a new tag.
Tracking BAR
Started 2020-09-01T07:43:44
Current                  44
Total               0:00:00
$ timew summary :all
Wk  Date       Day Tags …
```

CmdSummary: Fix calculation of display start in summary table

---

README.md

Following the Readme.md to download the tarball in order to build and install timewarrior 1.4.2 I've recognized that the download URL has changed. This PR reflect the change. I've updated the Readme to fit version 1.4.2. Please accept this PR if you like the change.
Maybe you could backport this change to the branch for 1.4.2 as well.
Thanks!

Fixed URL for tarball download

---

test/basetest/utils.py

Python added Thread.is_alive() in 2.6 and removed Thread.isAlive() in
3.9.
This change is needed to run the tests with Python 3.9.
https://bugs.python.org/issue37804
Signed-off-by: Shaun Ruffell <sruffell@sruffell.net>

test: Thread.isAlive() -> Thread.is_alive()

---

src/Datafile.cpp
src/data.cpp
test/docker/opensuse1500
test/modify.t

The fundamental change is to prevent marking the latest "real" interval as a synthetic interval in this case. 
Closes #422

Fix encode/decode failure when modifying open interval inside exclusion

---

src/data.cpp
test/export.t
test/modify.t

Sorry about this, I made a mistake in #423 where getTracked wouldn't return some intervals that intersect with the filter. I also addressed your notes about the unused variables in test/modify.t
Hopefully this can make it in 1.4.3 before you tag.

Cleanup for PR 423

---

CONTRIBUTING.md
README.md

This PR adds badges into relevant sections of the README file in order to provide information about the state of the repo that is of dynamic nature (last versions in certain distributions, community channels, etc.).
Also adds a community section.
This makes the README's style consistent with `taskwarrior`.

README: Provide dynamic information through badges

---

src/AtomicFile.cpp
src/AtomicFile.h

This change just fixes a few minor things in AtomicFile. Primarily to eliminate unnecessary code and make the impl private in the AtomicFile class.

Minor AtomicFile cleanup

---

doc/man1/timew-chart.1.adoc
doc/man1/timew-tags.1.adoc

Adds this into `man timew-tags`:
```
CONFIGURATION
tags.<tag>.color
Assigns a specific foreground and background color to a tag, instead of the default color palette determined by your current theme.
Examples of valid colors include 'white', 'gray8', 'black on yellow', and 'rgb345'.
```

Add man documentation for configuring tag colors.

---

doc/man1/timew-summary.1.adoc
src/Chart.cpp
src/commands/CmdSummary.cpp
src/helper.cpp
src/timew.h

Uses the existing `intervalColor` function. Includes documentation consistent with CmdTags and CmdChart.
Closes #459.

Add colors to summary

---

src/IntervalFilter.h
src/IntervalFilterAllInRange.cpp
src/IntervalFilterAllInRange.h
src/IntervalFilterAndGroup.cpp
src/IntervalFilterAndGroup.h
src/commands/CmdChart.cpp
src/commands/CmdExport.cpp
src/commands/CmdReport.cpp
src/commands/CmdSummary.cpp
src/commands/CmdTags.cpp
src/dom.cpp

This eliminates the use of the naked "new" so that when the filters object is
destroyed, the filters are also freed.
This also eliminates a potential issue with binding an r-value reference to a
Range as a reference in IntervalFilterAllInRange.

Do not leak IntervalFilters in IntervalFilterAndGroup

---

.github/workflows/docker-image.yaml
docker/timew.dockerfile

Add a GitHub workflow to create a Docker image with a Timewarrior installation
The workflow is triggered by a successful run of the test suite and creates a Docker image with a Timewarrior installation of the current branch (restricted to develop/stable)
Signed-off-by: Thomas Lauf <thomas.lauf@tngtech.com>

Add workflow for Timewarrior Docker image

---

src/commands/CmdSummary.cpp
test/summary.t

When calling `summary` command with `:annotations` hint, if the annotation is longer than a certain length, it's going to be truncated. The issue is that the length and truncation are done on a raw string without considering UTF8 multibyte characters, so there are edge cases when an annotation is truncated in the middle of a character creating an invalid UTF8 string.
Fixes #485.
~~The fix is trivial, but~~ I have doubts about the test case - I wrote whatever the first thing which came to my mind. Open to feedback in that regard.
Based on the context, we might want to use `utf8_width`, because we care more about how wide the text appears in the output. However, since we can't (or I don't know how to) split the text by width, but we do it by length of characters, I decided to use …

Fix summary truncating multibyte characters in long anotations
